package pmdRules;

/**
 * Read in a pmd-report.xml file generated by a SonarQube scan
 */
public class PMDReportXMLParser {

    private static String TEST_PROJECT_DIR = "pmdRuleTestFiles/delphi-test-project/";
    private static String PMD_REPORT_FILE = ".scannerwork/pmd-report.xml";

    private void parsePmdReportXML(){
        
    }


}
